/* Original editorial itineraries. Shared day modules are deliberately reused across trip lengths. */
const V3_TRAVEL_SOURCE='https://www.sz.gov.cn/en_szgov/life/cultural/cultural/';
const v3Day=(id,zh,en,areaZh,areaEn,stopsZh,stopsEn,tipZh,tipEn,cover,map)=>({id,title:bi(zh,en),area:bi(areaZh,areaEn),stops:bi(stopsZh,stopsEn),note:bi(tipZh,tipEn),cover:'assets/scene-'+cover+'-v3.webp',map});
const V3_DAYS={
 f:v3Day('f','福田中轴线：从山顶读一座城','Futian skyline from above','福田','Futian',['09:30 莲花山公园，慢走到观景处','12:00 福田午餐与休息','14:00 市民中心建筑漫步，傍晚在中心区用餐'],['09:30 Walk through Lianhua Hill Park to a viewpoint','12:00 Lunch and a break in Futian','14:00 Explore Civic Center architecture; dine nearby in the evening'],'穿适合步行的鞋；登高有坡度，热天减少中午户外时间。','Wear walking shoes; expect slopes and avoid midday heat.','hill','莲花山公园'),
 n:v3Day('n','南头古城：小巷、展览与咖啡','Nantou: lanes, exhibitions & coffee','南山','Nanshan',['10:00 南头古城，从城门走入街区','12:30 古城附近午餐','14:00 挑一间开放的展馆或书店，16:00 咖啡小憩'],['10:00 Enter Nantou Ancient Town through the old gate','12:30 Lunch near the historic quarter','14:00 Browse an open exhibition or bookshop; coffee at 16:00'],'商店与展馆独立营业，提前查想看的展览；无需每条巷子都走完。','Shops and venues keep separate hours. Choose an exhibition and leave room to wander.','oldtown','南头古城'),
 b:v3Day('b','深圳湾：把一天交给海风','Shenzhen Bay: an easy coastal day','南山 / 福田','Nanshan / Futian',['10:00 选深圳湾公园一个入口，沿海慢走','12:00 离开海边吃饭，避开日晒','16:00 返回一段喜欢的海岸，看黄昏光线'],['10:00 Choose a Shenzhen Bay Park entrance and walk one stretch','12:00 Lunch inland and a break from the sun','16:00 Return to a favorite waterfront section for evening light'],'这是轻步行线，不是全海岸徒步。先选出口，日落与观鸟均视天气季节而定。','This is a gentle walk, not the full coastline. Plan an exit; sunset and birdlife vary.','coast','深圳湾公园'),
 s:v3Day('s','蛇口：海上世界的国际日常','Shekou: a neighborhood of global flavors','南山 · 蛇口','Nanshan · Shekou',['10:00 海上世界周边散步，认识街区','12:00 选择一种国际风味午餐','15:00 海边休息，选一间咖啡馆，晚餐留在蛇口'],['10:00 Explore the streets around Sea World','12:00 Choose an international lunch','15:00 A waterfront pause and coffee; stay in Shekou for dinner'],'海上世界是蛇口街区名称，不是海洋馆。不要与小梅沙海洋世界混淆。','Sea World here is a Shekou neighborhood, not the Xiaomeisha aquarium.','coast','蛇口海上世界'),
 o:v3Day('o','OCT-LOFT：旧厂房里的灵感日','OCT-LOFT: design among former factories','南山 · 华侨城','Nanshan · OCT',['10:00 创意文化园街区漫步','12:30 园区附近吃饭','14:00 按当期开放情况看展、逛书店，16:00 坐下来喝咖啡'],['10:00 Walk around the creative district','12:30 Lunch nearby','14:00 Visit open exhibitions and bookshops; coffee at 16:00'],'展览、演出另查当期日历；不要将手作课程当作已包含的体验。','Check current exhibition and performance calendars. Workshops are not included by default.','art','华侨城创意文化园'),
 y:v3Day('y','大梅沙：今天的主题只有海','Dameisha: a day devoted to the sea','盐田','Yantian',['09:00 从市区出发，预留跨区交通','11:00 核对大梅沙开放后安排海边散步','14:00 午餐与休息，16:00 选开放的滨海步道，提早返回'],['09:00 Leave the center with a generous travel buffer','11:00 Check Dameisha access before a beach walk','14:00 Lunch and rest; an open promenade at 16:00, then return'],'天气不佳不安排海滨活动；不要与大鹏拼成同一天。','Skip coastal activities in bad weather. Do not squeeze Dapeng into this day.','coast','大梅沙海滨公园'),
 d:v3Day('d','大鹏所城：去城墙里过慢一天','Dapeng Fortress: a slower historic day','大鹏新区','Dapeng',['09:00 提前确认交通后出发','11:00 大鹏所城，城门与老街慢看','13:00 午餐；15:00 较场尾附近休息，给返程留时间'],['09:00 Depart after confirming transport','11:00 Explore Dapeng Fortress gates and lanes','13:00 Lunch; a 15:00 break around Jiaochangwei before returning'],'这是独立长途日。自驾需查当期预约安排，实际车程受路况影响。','Dedicate a full day. Check current driving access rules and allow for traffic.','fortress','大鹏所城'),
 g:v3Day('g','甘坑：客家街巷与凉帽故事','Gankeng: Hakka lanes and craft stories','龙岗','Longgang',['10:00 甘坑古镇漫步','12:00 客家风味午餐，先说明口味偏好','14:00 找开放的传统文化展陈与小店，下午返回'],['10:00 Walk through Gankeng','12:00 Hakka lunch, adjusted to your preferences','14:00 Look for open cultural displays and shops, then return'],'手作项目是否开展、是否收费请现场确认；不预设任何课程已预订。','Confirm craft activity availability and fees on site; no class is pre-booked.','oldtown','甘坑古镇'),
 l:v3Day('l','罗湖：老深圳的街头滋味','Luohu: street life and familiar flavors','罗湖','Luohu',['10:00 东门步行街，先走一圈再决定买什么','12:00 选择一家明码标价的餐厅','14:00 逛街与茶歇，傍晚返回酒店或前往罗湖周边用餐'],['10:00 Browse Dongmen before deciding what to buy','12:00 Choose a restaurant with clear menu prices','14:00 Shops and a tea break; dinner around Luohu'],'商业街人流较多，少带行李；点餐和购物前确认总价。','Expect busy shopping streets. Travel light and confirm totals before ordering.','oldtown','东门老街'),
 a:v3Day('a','大芬：走进画里的下午','Dafen: a day among paintings','龙岗 · 布吉','Longgang · Buji',['10:00 大芬油画村街区散步','12:00 午餐休息','14:00 看画廊与创作空间，询问画作工艺后再购买'],['10:00 Explore Dafen Oil Painting Village','12:00 Lunch and a break','14:00 Browse galleries and studios; ask about technique before buying'],'参观创作空间和拍照先征求同意；画作原创性、装裱和运输单独确认。','Ask before photographing studios. Clarify originality, framing and shipping.','art','大芬油画村'),
 q:v3Day('q','欢乐港湾：西部海岸的黄昏','OH Bay: western waterfront light','宝安','Bao’an',['10:30 宝安中心区慢逛','12:30 午餐和室内休息','16:00 欢乐港湾海滨漫步；摩天轮需另查门票和运行信息'],['10:30 An easy walk in central Bao’an','12:30 Lunch and an indoor break','16:00 OH Bay waterfront; check wheel tickets and operation separately'],'摩天轮不包含在建议预算内；海边天气与设施运营可能变化。','The wheel is not included in the suggested budget. Weather and operations can change.','coast','欢乐港湾'),
 p:v3Day('p','观澜：版画与乡村肌理','Guanlan: printmaking and village textures','龙华 · 观澜','Longhua · Guanlan',['09:30 前往观澜版画村','11:00 看传统村落与公共空间','13:00 午餐后按开放情况看版画展，15:30 准备返程'],['09:30 Travel to Guanlan Print Art Village','11:00 Explore traditional village spaces','13:00 Lunch, then open print exhibitions; prepare to return at 15:30'],'从市中心出发需留交通余量。展馆与制作体验的开放、预约另行核实。','Allow extra travel time from the center. Check venue access and workshops separately.','art','观澜版画村'),
 m:v3Day('m','深圳博物馆：给城市补一段背景','Shenzhen Museum: the city in context','福田','Futian',['09:30 按预约前往深圳博物馆指定场馆','12:00 市民中心附近午餐','14:00 以室内阅读和城市建筑散步收尾'],['09:30 Visit the specifically booked Shenzhen Museum venue','12:00 Lunch around Civic Center','14:00 Indoor reading and a short architecture walk'],'先确认场馆、开放日和预约，闭馆时改为休闲午餐与建筑外观漫步。','Verify the venue, opening day and booking. If closed, substitute lunch and exterior architecture.','art','深圳博物馆历史民俗馆'),
 t:v3Day('t','海岸城：茶礼、点心与城市购物','Coastal City: tea, dim sum and shopping','南山 · 后海','Nanshan · Houhai',['10:30 海岸城周边逛店','12:00 港式点心午餐','14:00 选购小件茶礼或日用品，留一段咖啡时间'],['10:30 Browse around Coastal City','12:00 Hong Kong-style dim sum lunch','14:00 Look for tea gifts and useful finds, then coffee'],'这是商圈慢游，不承诺任何品牌门店或促销持续营业。','A relaxed shopping-area plan; no specific brand presence or promotion is guaranteed.','art','海岸城购物中心'),
 r:v3Day('r','福田美食：一盅两件到晚餐','Futian food day: tea to dinner','福田','Futian',['10:00 广式早茶，少量多样点单','13:00 酒店或咖啡馆午休','16:00 中心区轻松散步，18:00 选择粤菜晚餐'],['10:00 Dim sum brunch, ordered in small portions','13:00 Rest at your hotel or a cafe','16:00 An easy central walk; Cantonese dinner at 18:00'],'餐厅按本页 POI 选择并提前核实；过敏、忌口和价格向店员确认。','Choose a POI and confirm details. Discuss allergies, dietary needs and prices with staff.','oldtown','福田中心区'),
 c:v3Day('c','深圳湾摄影：同一片海，两种光线','Bay photography: one coast, two lights','南山','Nanshan',['08:00 选择海边一段晨光，随季节调整','11:00 离开海边午餐，整理照片与休息','16:00 返回同片区拍黄昏，天气不适合则改为咖啡馆'],['08:00 Morning waterfront light, adjusted for the season','11:00 Lunch, photo sorting and rest inland','16:00 Evening photos in the same area, or a cafe in poor weather'],'不保证日出日落效果；拍摄人物先取得同意，不进入封闭区域。','Light is weather-dependent. Ask before photographing people and respect closed areas.','coast','深圳湾公园'),
 h:v3Day('h','大万世居：另一种客家深圳','Dawan: another side of Hakka Shenzhen','坪山','Pingshan',['09:30 向坪山出发','11:00 大万世居周边看客家建筑','13:00 午餐；按开放情况看展陈，15:30 返回'],['09:30 Travel towards Pingshan','11:00 Explore the Hakka architecture around Dawan','13:00 Lunch and any open displays; return around 15:30'],'适合想看传统建筑的人；入内、展览与活动需提前确认，不与西部景点拼日。','For traditional architecture lovers. Verify interior access and exhibitions; avoid adding western districts.','fortress','大万世居'),
 z:v3Day('z','留白日：重访喜欢的一站','A flexible day: return to a favorite','酒店周边','Near your hotel',['10:00 酒店附近早茶或重访喜欢的街区','13:00 手信选购，检查包装与保质期','15:00 休息、打包，或为下一段旅程预留交通时间'],['10:00 Tea near your hotel or revisit a favorite area','13:00 Gift shopping; check packaging and shelf life','15:00 Rest, pack or leave time for onward transport'],'不安排远距离新景点；出发时间与行李要求以承运方为准。','Avoid new distant attractions. Confirm departure and luggage requirements with your carrier.','art','深圳市民中心')
};
const V3_THEMES=[
 {id:'skyline',name:bi('城市天际线','Skyline stories'),title:bi('深圳初见，从城市中轴开始','First impressions, along the city axis'),keys:['f','m','n','q','o','s','z'],tag:bi('建筑与城市','Architecture & city'),note:bi('把建筑和城市历史放在前面，海边留到下午。','Lead with architecture and history; save the coast for the afternoon.')},
 {id:'oldtown',name:bi('古城与街巷','Old-town lanes'),title:bi('别只看高楼，去深圳的老街走走','Look beyond the towers, into the old lanes'),keys:['n','d','g','l','h','p','z'],tag:bi('历史与文化','History & culture'),note:bi('每天选一片老街，不把东部古城和西部街区挤在一天。','One historic area per day; separate eastern forts and western neighborhoods.')},
 {id:'bay',name:bi('海湾慢生活','Life by the bay'),title:bi('把时间放慢，沿着深圳的海走','Slow down and follow the Shenzhen coast'),keys:['b','s','q','y','d','c','z'],tag:bi('轻松看海','Easy coastal days'),note:bi('每天只走一段海岸，中午留给休息。','Choose one coastal stretch per day and rest at midday.')},
 {id:'world',name:bi('国际街区','Global neighborhoods'),title:bi('从蛇口开始，吃遍城市的世界风味','Start in Shekou, taste a world of flavors'),keys:['s','r','t','l','o','n','z'],tag:bi('街区与餐桌','Neighborhoods & food'),note:bi('以餐桌和街区为主线，不把任何餐厅当作已预约。','Connect neighborhoods through food; no restaurant reservation is implied.')},
 {id:'design',name:bi('设计灵感','Design discoveries'),title:bi('给灵感放假，钻进深圳的创意街区','A creative escape into Shenzhen’s design districts'),keys:['o','a','p','n','m','s','z'],tag:bi('艺术与书店','Art & bookshops'),note:bi('先查当期展览，再决定当天的小店与咖啡停留。','Check exhibitions first, then make room for shops and coffee.')},
 {id:'beach',name:bi('东部海岸','Eastern coast'),title:bi('向东走，把海边的日子过舒服','Head east for unhurried seaside days'),keys:['y','d','h','g','l','r','z'],tag:bi('沙滩与古城','Beach & heritage'),note:bi('东部远途日分开安排，恶劣天气改室内。','Keep eastern day trips separate; use indoor alternatives in poor weather.')},
 {id:'fortress',name:bi('城墙与人文','Forts & stories'),title:bi('去大鹏，寻找海防古城里的旧故事','Dapeng and the stories within old walls'),keys:['d','h','g','p','m','n','z'],tag:bi('古建筑主题','Historic architecture'),note:bi('关注建筑外观与日常生活，展馆入内需另行确认。','Focus on architecture and everyday life; verify indoor venue access.')},
 {id:'hakka',name:bi('客家拾光','Hakka discoveries'),title:bi('客家故事不止一站，慢慢看才有味道','Hakka stories, one thoughtful stop at a time'),keys:['g','h','p','a','l','d','z'],tag:bi('传统与手作','Tradition & craft'),note:bi('手作是否开放及收费现场确认，传统村落内尊重居民生活。','Confirm craft access and fees, and respect residents in traditional villages.')},
 {id:'streetfood',name:bi('街头烟火','Street-life flavors'),title:bi('从罗湖出发，用几顿饭认识深圳','Meet Shenzhen through its streets and meals'),keys:['l','r','t','g','n','s','z'],tag:bi('吃逛不赶路','Eat, browse, pause'),note:bi('食量不同就灵活减少餐点，餐前确认过敏原与总价。','Adjust meal stops to your appetite; confirm allergens and totals.')},
 {id:'art',name:bi('画里的深圳','An artist’s Shenzhen'),title:bi('画廊、版画与老厂房，艺术迷这样逛','Galleries, prints and old factories for art lovers'),keys:['a','p','o','m','n','h','z'],tag:bi('画作与工艺','Painting & craft'),note:bi('欣赏与购买分开安排，拍照先问、画作来源先确认。','Separate looking from buying; ask before photos and verify artwork provenance.')},
 {id:'west',name:bi('西部假日','Western weekend'),title:bi('欢乐港湾见，西部海岸也很会过周末','Meet at OH Bay for a western waterfront escape'),keys:['q','n','t','s','b','o','z'],tag:bi('宝安与南山','Bao’an & Nanshan'),note:bi('优先住在行程西侧以减少通勤，付费设施另行购票。','A western base reduces travel; paid attractions need separate tickets.')},
 {id:'craft',name:bi('版画与慢村','Prints & quiet lanes'),title:bi('观澜出发，把手作和村落装进行程','From Guanlan, follow craft and village textures'),keys:['p','g','a','h','o','m','z'],tag:bi('安静文化线','Quiet cultural days'),note:bi('为城北与东部转移预留整段交通时间，避开紧凑打卡。','Allow proper travel time between northern and eastern areas; avoid rushing.')}
];
const V3_DURATION={half:bi('半日游','Half day'),one:bi('1 日游','1 day'),two:bi('2 日游','2 days'),three:bi('3 日游','3 days'),seven:bi('7 日游','7 days')};
const V3_ROUTES=Object.entries(V3_DURATION).flatMap(([duration,label])=>V3_THEMES.map((theme,i)=>{
 const count={half:1,one:1,two:2,three:3,seven:7}[duration];const days=theme.keys.slice(0,count).map(k=>V3_DAYS[k]);
 const first=days[0];const half=duration==='half';
 const baseTitle=half?bi(pickStatic(first.area,'zh')+'半日｜'+pickStatic(theme.name,'zh'),pickStatic(theme.name,'en')+' · Half a day'):theme.title;
 const halfDay={...first,title:bi(pickStatic(first.title,'zh')+' · 半日轻量版',pickStatic(first.title,'en')+' · Short visit'),stops:bi(['14:00 在目的地区域集合，选择一段街区或公园漫步','15:30 茶歇，按当日开放情况选一个文化或观景停留','17:00 附近用餐或返程，不再跨区赶第二个景点'],['14:00 Start in the destination area and choose a neighborhood or park walk','15:30 A tea break and one open cultural or scenic stop','17:00 Dine nearby or return; avoid adding a second district']),note:bi('半日指抵达 '+first.area.zh+' 后约 3–4 小时，不含从酒店往返交通。目的地：'+first.map+'。'+first.note.zh,'Allow 3–4 hours after arrival in '+first.area.en+', excluding hotel transfers. Destination: '+first.title.en+'. '+first.note.en)};
 const budgets={half:[60,160],one:[130,300],two:[260,600],three:[400,900],seven:[1000,2400]};
 return {id:duration+'-'+theme.id,duration,title:baseTitle,theme:theme.name,tags:[theme.tag,first.area],cover:first.cover,area:first.area,days:half?[halfDay]:days,lead:bi(theme.note.zh+(half?' 只在一个片区停留，适合已有明确集合点的旅客。':' 按片区安排，不在同一天往返城市两端。'),theme.note.en+(half?' Stay in one area, with a clear starting point.':' Plan by area rather than crossing the whole city in a day.')),tip:theme.note,budget:budgets[duration],index:i+1,source:V3_TRAVEL_SOURCE};
}));
function pickStatic(value,language){return value[language];}
const HALF_STOPS={
 f:bi(['14:00 莲花山公园，从林荫路慢走登高','15:30 山下休息，前往市民中心看建筑外观','17:00 在福田中心区吃晚餐后返回'],['14:00 Lianhua Hill Park: a shaded uphill walk','15:30 Rest below the hill, then view Civic Center architecture','17:00 Dinner in central Futian before returning']),
 n:bi(['14:00 南头古城城门集合，走进老街','15:00 选择一间开放的小展馆或设计店','16:30 古城咖啡与点心，步行原路返回'],['14:00 Meet at Nantou’s gate and explore the lanes','15:00 Choose an open small exhibition or design shop','16:30 Coffee and a snack before walking back']),
 b:bi(['15:00 深圳湾公园选定入口，沿水边走一段','16:00 找休息区看海，减少曝晒','17:00 随当日光线拍照，再从附近出口离开'],['15:00 Enter a chosen section of Shenzhen Bay Park','16:00 Rest with a sea view and keep out of strong sun','17:00 Take photos in the available light, then leave nearby']),
 s:bi(['14:00 海上世界广场集合，绕明华轮周边看街景','15:00 蛇口街区咖啡或轻食','16:30 海边慢走，选一家国际餐厅晚餐'],['14:00 Meet at Sea World and explore around the Minghua ship','15:00 Coffee or a light bite in Shekou','16:30 A coastal stroll, then an international dinner']),
 o:bi(['14:00 OCT-LOFT 看旧厂房外观与公共空间','15:00 逛书店或开放的设计展','16:30 在园区咖啡馆坐一会儿再返回'],['14:00 Former factories and public spaces at OCT-LOFT','15:00 Browse a bookshop or an open design show','16:30 A cafe pause before heading back']),
 y:bi(['14:00 抵达大梅沙，先核对沙滩入口开放情况','15:00 沿开放海滨区域散步，随时休息','16:30 在盐田吃一餐，再按已安排的交通返回'],['14:00 Arrive at Dameisha and check beach access','15:00 Walk the open waterfront with plenty of breaks','16:30 Eat in Yantian, then use your planned return transport']),
 d:bi(['14:00 已抵达大鹏所城，从城门进入','15:00 慢看老街与开放的历史建筑','16:30 所城附近吃饭或茶歇，按预约交通返回'],['14:00 Start after arriving at Dapeng Fortress','15:00 Explore old lanes and accessible historic buildings','16:30 A meal or tea nearby, then your arranged return']),
 g:bi(['14:00 甘坑古镇入口集合，沿主街慢走','15:00 寻找凉帽文化与客家主题展陈','16:30 选一家客家小店吃东西后返回'],['14:00 Start at Gankeng’s entrance and walk the main lanes','15:00 Look for summer-hat and Hakka displays','16:30 A Hakka-style snack or meal before returning']),
 l:bi(['14:00 东门老街集合，先观察店铺与菜单','15:00 少量尝味，选择明码标价的小吃','16:30 街区购物或茶歇，避开携带大件行李'],['14:00 Meet at Dongmen and browse shops and menus','15:00 Try a small snack with clearly displayed prices','16:30 Light shopping or tea; leave large luggage elsewhere']),
 a:bi(['14:00 大芬油画村散步，看画廊橱窗','15:00 在允许参观的画廊看作品','16:30 咖啡休息，购买前询问画作来源与包装'],['14:00 Walk past gallery windows in Dafen','15:00 Visit galleries that welcome entry','16:30 Coffee; ask about provenance and packing before buying']),
 q:bi(['15:00 欢乐港湾滨海区域集合','16:00 看公共艺术与海岸线，摩天轮另行决定','17:00 海边晚餐，看天气选择返程时间'],['15:00 Meet at OH Bay’s waterfront','16:00 Public art and coastal views; wheel visit is optional','17:00 Dinner by the bay, returning as weather allows']),
 p:bi(['14:00 已抵达观澜版画村，先走传统村落','15:00 按开放情况参观版画展陈','16:30 村落附近休息，为市区返程预留时间'],['14:00 Start after arriving at Guanlan Print Art Village','15:00 Visit print displays when open','16:30 Rest nearby and leave time for the journey back'])
};
for(const r of V3_ROUTES.filter(r=>r.duration==='half')){const key=V3_THEMES[r.index-1].keys[0];r.days[0].stops=HALF_STOPS[key];}
