'use strict';
const stateV3={duration:'half',route:null,foodSearch:'',foodCuisine:'all',reviewOnly:false,foodPage:1,contactProduct:null};
const productImage=g=>`assets/product-${String(GIFTS.indexOf(g)+1).padStart(2,'0')}-v3.webp`;
const attr=esc;
const chipsV3=(items,key,current)=>`<div class="filter-chips" role="group" aria-label="${key}">${items.map(([id,label])=>`<button type="button" data-v3="${key}" data-value="${id}" aria-pressed="${current===id}">${label}</button>`).join('')}</div>`;
function dialogV3(id,wide=false){let node=document.getElementById(id);if(!node){node=document.createElement('dialog');node.id=id;node.className=wide?'v3-dialog wide-dialog':'v3-dialog';document.body.append(node);node.addEventListener('click',e=>{if(e.target===node){const box=node.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)node.close();}});}return node;}
function dialogHeader(title){return `<div class="dialog-top"><h2>${title}</h2><button class="close" data-v3="close-dialog" aria-label="${say('关闭','Close')}">×</button></div>`;}
function showImageV3(src,alt){const node=dialogV3('image-dialog',true);node.innerHTML=dialogHeader(say('完整图片','Full image'))+`<img class="full-image" src="${attr(src)}" alt="${attr(alt)}"><p class="fine-print">${say('手机可长按图片保存。','On mobile, long-press the image to save.')}</p>`;node.showModal();}
function enhanceImagesV3(){document.querySelectorAll('.hero-visual>img,.portrait img').forEach(img=>{img.tabIndex=0;img.setAttribute('role','button');img.setAttribute('aria-label',say('查看完整图片：','View full image: ')+img.alt);img.dataset.v3='image';});}
function contactsV3(context=''){return `<div class="real-contacts"><div class="contact-heading"><span class="eyebrow">LET’S TALK</span><h4>${say('扫码联系，聊聊你的计划','Scan to talk about your plans')}</h4>${context?`<p>${esc(context)}</p>`:''}</div>${Object.entries(CONTACTS).map(([key,c])=>`<article class="contact-option"><button class="qr-view" data-v3="qr" data-value="${key}" aria-label="${say('查看完整','View full')} ${c.label} ${say('二维码','QR code')}"><img src="${c.image}" alt="${c.label} ${say('联系二维码','contact QR code')}" width="320" height="320" loading="lazy"></button><strong>${c.label}</strong>${c.url?`<a class="secondary" href="${attr(c.url)}" target="_blank" rel="noopener noreferrer">${say('打开聊天','Open chat')} ↗</a>`:`<button class="secondary" data-v3="qr" data-value="${key}">${say('查看二维码','View QR code')}</button>`}</article>`).join('')}</div>`;}
contactBlank=function(){return contactsV3();};
function routeUrlV3(r){const url=new URL(location.href);url.search='';url.searchParams.set('lang',lang);url.searchParams.set('route',r.id);url.hash='travel';return url.href;}
function routeTextV3(r){return [pick(r.title)+' · '+pick(V3_DURATION[r.duration]),pick(r.lead),...r.days.flatMap((d,i)=>['\nDAY '+(i+1)+' · '+pick(d.title),...pick(d.stops),pick(d.note)]),'\n'+say('编辑建议行程，交通与开放信息出发前确认。','An editorial itinerary; confirm transport and venue access before travel.'),routeUrlV3(r)].join('\n');}
renderTravelV2=function(){
 const routes=V3_ROUTES.filter(r=>r.duration===stateV3.duration);
 document.querySelector('#panel-travel').innerHTML=panelHeading('SIXTY WAYS TO MEET SHENZHEN',say('把深圳，玩成你的样子','Find your Shenzhen story'),say('五种时长，每种 12 条路线。点开一篇，把下一次出发安排好。','Five trip lengths, 12 routes each. Open a note and make a plan.'))+chipsV3(Object.entries(V3_DURATION).map(([id,label])=>[id,pick(label)]),'duration',stateV3.duration)+`<div class="collection-bar"><span>${routes.length} ${say('条路线 · 每条都有逐日攻略','routes · Each with a day-by-day guide')}</span><span>${say('城市 / 山海 / 艺术 / 文化','City / Coast / Art / Culture')}</span></div><div class="route-grid">${routes.map((r,i)=>`<article class="route-tile theme-${i%4}"><button class="route-cover" data-v3="open-route" data-value="${r.id}" aria-label="${attr(pick(r.title))}"><img src="${r.cover}" width="1536" height="1024" alt="${attr(pick(r.theme))} · ${say('AI 旅行意境图','AI travel impression')}" loading="lazy"><span class="route-length">${pick(V3_DURATION[r.duration])}</span><span class="cover-caption">${pick(r.theme)}</span><small class="art-mark">AI</small></button><div class="route-tile-body"><span class="tile-area">⌖ ${pick(r.area)}</span><button class="route-title-button" data-v3="open-route" data-value="${r.id}"><h4>${pick(r.title)}</h4></button><p class="tile-stops">${r.days.map(d=>pick(d.area)).filter((v,i,a)=>a.indexOf(v)===i).join(' · ')}</p><div class="tile-bottom"><span># ${pick(r.tags[0])}</span><button class="share-mini" data-v3="share-route" data-value="${r.id}" aria-label="${say('分享','Share')} ${attr(pick(r.title))}">↗ <span>${say('分享','Share')}</span></button></div></div></article>`).join('')}</div>`;
};
function openRouteV3(id){
 const r=V3_ROUTES.find(r=>r.id===id);if(!r)return;stateV3.route=id;stateV3.duration=r.duration;
 const node=dialogV3('route-dialog',true);
 node.innerHTML=dialogHeader(pick(V3_DURATION[r.duration])+' · '+pick(r.theme))+`<div class="route-detail"><button class="detail-image" data-v3="full-route-image" data-value="${r.id}" aria-label="${say('查看完整封面图','View complete cover image')}"><img src="${r.cover}" width="1536" height="1024" alt="${attr(pick(r.theme))} · AI"><span>${say('查看原图 · AI 意境图','View full image · AI impression')} ↗</span></button><div class="route-detail-body"><p class="eyebrow dark">SHENZHEN CITY NOTES · 2026</p><h3>${pick(r.title)}</h3><p class="note-lead">${pick(r.lead)}</p><div class="note-tags">${r.tags.map(t=>`<span># ${pick(t)}</span>`).join('')}</div><div class="trip-stats"><div><small>${say('时长 / 强度','DURATION / PACE')}</small><strong>${pick(V3_DURATION[r.duration])} · ${say('慢行与公共交通','Walking & public transport')}</strong></div><div><small>${say('餐饮和市内交通预算','MEALS & CITY TRANSPORT')}</small><strong>¥${r.budget[0]}–${r.budget[1]} / ${say('人','person')}</strong></div></div><p class="fine-print">${say('编辑估算，不含住宿、往返深圳交通、门票和地陪，不是服务报价。','Editorial estimate, excluding hotels, travel to Shenzhen, admission and guides. Not a service quote.')}</p>${r.days.map((d,i)=>`<section class="day-block"><span class="day-marker">${r.duration==='half'?'½':i+1}</span><div><span class="eyebrow dark">DAY ${String(i+1).padStart(2,'0')}</span><h4>${pick(d.title)}</h4><ol>${pick(d.stops).map(s=>`<li>${s}</li>`).join('')}</ol><p class="day-tip">${pick(d.note)}</p><a class="source-link" href="${mapLink(d.map)}" target="_blank" rel="noopener noreferrer">${say('地图导航','Open map')} ↗</a></div></section>`).join('')}<aside class="editor-tip"><strong>${say('旅行笔记','Travel note')}</strong><p>${pick(r.tip)}</p></aside><div class="detail-actions"><button class="primary" data-v3="share-route" data-value="${r.id}">${say('分享攻略','Share itinerary')} ↗</button><button class="secondary" data-v3="route-to-guide" data-value="${r.id}">${say('按这条路线找地陪','Plan with a guide')}</button></div>${contactsV3(pick(r.title))}</div></div>`;
 if(!node.open)node.showModal();node.scrollTop=0;const url=new URL(location.href);url.searchParams.set('route',id);url.hash='travel';history.replaceState(null,'',url);
 node.onclose=()=>{const url=new URL(location.href);url.searchParams.delete('route');history.replaceState(null,'',url);document.querySelector(`[data-v3="open-route"][data-value="${id}"]`)?.focus({preventScroll:true});};
}
function shareRouteV3(id){const r=V3_ROUTES.find(r=>r.id===id);if(!r)return;stateV3.route=id;const text=routeTextV3(r),url=routeUrlV3(r);const node=dialogV3('share-dialog');node.innerHTML=dialogHeader(say('把攻略分享给朋友','Share this trip with a friend'))+`<p>${pick(r.title)}</p><div class="share-platforms"><a class="platform-whatsapp" href="https://wa.me/?text=${encodeURIComponent(pick(r.title)+'\n'+url)}" target="_blank" rel="noopener noreferrer">WhatsApp ↗</a><a class="platform-telegram" href="https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(pick(r.title))}" target="_blank" rel="noopener noreferrer">Telegram ↗</a></div><label class="share-label" for="share-text">${say('攻略文本','Itinerary text')}</label><textarea id="share-text" readonly>${esc(text)}</textarea><div class="copy-actions"><button class="secondary" data-v3="copy-link" data-value="${r.id}">${say('复制链接','Copy link')}</button><button class="secondary" data-v3="copy-text" data-value="${r.id}">${say('复制完整攻略','Copy full itinerary')}</button></div><p class="status" id="share-status" role="status"></p>`;node.showModal();}
const V3_CUISINES={all:bi('全部菜系','All cuisines'),chinese:bi('中式风味','Chinese regional'),dimsum:bi('早茶点心','Dim sum'),cantonese:bi('粤菜中餐','Cantonese / Chinese'),hotpot:bi('火锅','Hot pot'),seafood:bi('海鲜','Seafood'),western:bi('西式餐饮','Western'),japanese:bi('日式','Japanese'),indian:bi('印度菜','Indian'),cafe:bi('咖啡轻食','Cafe')};
function getFoodV3(){const origin=stateV2.location||ORIGINS.find(o=>o.id===stateV2.origin);return V3_RESTAURANTS.filter(r=>r.group===stateV2.foodGroup).filter(r=>stateV3.foodCuisine==='all'||r.dishCategory===stateV3.foodCuisine).filter(r=>!stateV3.reviewOnly||r.reviewTextEn||r.reviewTextZh).filter(r=>(r.nameZh+' '+r.nameEn+' '+r.areaZh+' '+r.areaEn).toLowerCase().includes(stateV3.foodSearch.toLowerCase().trim())).map(r=>({...r,distance:distanceKm(origin,r)})).sort((a,b)=>a.distance-b.distance||a.id.localeCompare(b.id));}
renderFoodV2=function(){
 const list=getFoodV3();const localCount=V3_RESTAURANTS.filter(r=>r.group==='local').length,taCount=V3_RESTAURANTS.filter(r=>r.group==='ta').length;
 const end=stateV3.foodPage*12;const visible=list.slice(0,end);const selected=stateV2.location?say('当前位置','Your location'):null;
 document.querySelector('#panel-food').innerHTML=panelHeading('GOOD FOOD, REAL VOICES',say('这一餐，听听吃过的人怎么说','Good meals. Voices from real visits.'),say('从菜品灵感到旅客原话，找到适合今天的一餐。','From cuisine inspiration to traveler excerpts, find your next meal.'))+filters([['local',say('本地推荐','Local picks')+' · '+localCount],['ta','Tripadvisor · '+taCount]],'foodGroup',stateV2.foodGroup)+`<div class="food-search-row"><label class="search-field"><span class="sr-only">${say('搜索餐厅或片区','Search restaurant or area')}</span><input id="food-search" type="search" value="${attr(stateV3.foodSearch)}" placeholder="${say('搜索餐厅 / 片区','Search restaurants / areas')}"></label><label><span class="sr-only">${say('菜系','Cuisine')}</span><select id="food-cuisine">${Object.entries(V3_CUISINES).map(([k,v])=>`<option value="${k}" ${k===stateV3.foodCuisine?'selected':''}>${pick(v)}</option>`).join('')}</select></label></div><div class="food-tools"><label>${say('距离起点','Distance from')}<select id="food-origin">${selected?`<option value="current" selected>${selected}</option>`:''}${ORIGINS.map(o=>`<option value="${o.id}" ${!selected&&o.id===stateV2.origin?'selected':''}>${pick(o.name)}</option>`).join('')}</select></label><button class="secondary" data-v2="locate" ${stateV2.locationStatus==='pending'?'disabled':''}>${stateV2.locationStatus==='pending'?say('定位中…','Locating…'):say('使用我的位置','Use my location')}</button><label class="review-switch"><input id="review-only" type="checkbox" ${stateV3.reviewOnly?'checked':''}>${say('只看有评论摘录','With review excerpts')}</label></div><p class="fine-print">${say('按起点到餐厅所在片区的近似直线距离排序，不是行车里程。定位仅用于本页。菜品图为 AI 菜系示意，非门店实拍。','Sorted by approximate direct distance to the restaurant area, not driving distance. Location stays on this page. Food images are AI cuisine illustrations, not venue photos.')}</p><p id="location-status" role="status" class="status">${locationMessage()}</p><div class="collection-bar"><span role="status">${list.length} ${say('家餐厅','restaurants')}</span><span>${say('近似距离优先','Approx. nearest first')}</span></div><div class="restaurant-grid">${visible.length?visible.map(r=>restaurantCardV3(r)).join(''):`<div class="empty-state"><h4>${say('没有找到匹配的餐厅','No restaurants match')}</h4><button class="secondary" data-v3="reset-food">${say('重置筛选','Reset filters')}</button></div>`}</div>${list.length>end?`<div class="load-more"><button class="secondary" data-v3="more-food">${say('再看 12 家','See 12 more')} · ${Math.min(end,list.length)}/${list.length}</button></div>`:''}`;
};
function restaurantCardV3(r){const zh=lang==='zh';const review=zh?r.reviewTextZh:r.reviewTextEn;const reviewUrl=r.reviewSource||r.source;const quoteNote=say('平台用户评论摘录 / 译文','Platform user excerpt / translation');return `<article class="restaurant-card"><button class="dish-picture" data-v3="dish-image" data-value="${r.dishCategory}" aria-label="${attr(pick(V3_CUISINES[r.dishCategory]))} ${say('示意图','illustration')}"><img src="assets/dish-${r.dishCategory}-v3.webp" width="1024" height="1024" alt="${attr(pick(V3_CUISINES[r.dishCategory]))} · ${say('AI 菜系示意，非门店实拍','AI cuisine illustration, not venue photography')}" loading="lazy"><span>${say('菜系示意 · AI','Cuisine illustration · AI')}</span></button><div class="restaurant-body"><div class="restaurant-meta"><span>${esc(zh?r.cuisineZh:r.cuisineEn)}</span><span>~${r.distance.toFixed(1)} km</span></div><h4>${esc(zh?r.nameZh:r.nameEn)}</h4><p class="restaurant-area">⌖ ${esc(zh?r.areaZh:r.areaEn)}</p>${review?`<blockquote><p>“${esc(review)}”</p><footer><span>${esc(r.reviewAuthor||say('平台用户','Platform user'))}${r.reviewDate?' · '+esc(r.reviewDate):''}</span><small>${quoteNote}</small></footer></blockquote>`:`<div class="review-unavailable"><p>${say('想了解口味与服务？前往门店资料页查看最新食客反馈。','Curious about the food and service? Check the venue page for current diner feedback.')}</p></div>`}<div class="restaurant-links"><a href="${attr(reviewUrl)}" target="_blank" rel="noopener noreferrer">${review?say('阅读完整评论','Read full review'):say('查看门店资料','View venue details')} ↗</a><a href="${mapLink(r.nameZh)}" target="_blank" rel="noopener noreferrer">${say('导航','Map')} ↗</a></div></div></article>`;}
renderGiftsV2=function(){
 const items=GIFTS.filter(g=>(stateV2.giftCategory==='all'||g.category===stateV2.giftCategory)&&(stateV2.budget==='all'||g.price<=Number(stateV2.budget))&&(stateV2.recipient==='all'||g.audience===stateV2.recipient)).sort((a,b)=>b.scores[stateV2.giftSort]-a.scores[stateV2.giftSort]||a.price-b.price);
 document.querySelector('#panel-gifts').innerHTML=panelHeading('A LITTLE CHINA, TO GO',say('让心意，有图有故事','Something thoughtful to take home'),say('看图片选心意，联系咨询实际款式、价格与配送。','Find a gift idea, then ask about the actual design, price and delivery.'))+filters(Object.entries(CATEGORY_LABELS).map(([k,v])=>[k,pick(v)]),'giftCategory',stateV2.giftCategory)+`<div class="gift-tools"><label>${say('榜单维度','Rank by')}<select id="gift-sort">${[['gift',say('送礼适配','Gift suitability')],['portable',say('轻装便携','Packability')],['culture',say('文化特色','Cultural character')]].map(([k,v])=>`<option value="${k}" ${k===stateV2.giftSort?'selected':''}>${v}</option>`).join('')}</select></label><label>${say('预算 / 件','Budget / item')}<select id="gift-budget">${[['all',say('不限','Any')],['100','≤ ¥100'],['200','≤ ¥200'],['300','≤ ¥300']].map(([k,v])=>`<option value="${k}" ${k===stateV2.budget?'selected':''}>${v}</option>`).join('')}</select></label><label>${say('送给谁','Recipient')}<select id="gift-recipient">${[['all',say('所有人','Anyone')],['friends',say('朋友 / 同事','Friends / colleagues')],['family',say('家人','Family')],['business',say('商务伙伴','Business contacts')]].map(([k,v])=>`<option value="${k}" ${k===stateV2.recipient?'selected':''}>${v}</option>`).join('')}</select></label></div><p class="fine-print">${say('图片为 AI 选礼示意，预算与排序为编辑建议；实际商品及价格请通过联系购买确认。','Images are AI gift concepts. Budgets and sorting are editorial suggestions; confirm actual products and prices via the contact button.')}</p><div class="product-grid">${items.length?items.map((g,i)=>`<article class="product-card"><button class="product-picture" data-v3="product-image" data-value="${g.id}" aria-label="${attr(pick(g.name))}"><img src="${productImage(g)}" width="1024" height="1024" alt="${attr(pick(g.name))} · ${say('AI 商品示意图','AI product concept')}" loading="lazy"><span class="product-tag">${pick(CATEGORY_LABELS[g.category])}</span><small class="art-mark">AI</small></button><div class="product-body"><h4>${pick(g.name)}</h4><p class="product-origin">${pick(g.origin)}</p><p class="product-description">${pick(g.desc)}</p><div class="product-price"><strong>≈ ¥${g.price}</strong><span>${say('计划预算','Planning budget')}</span></div><div class="product-fit">${say('编辑推荐','Editorial pick')} · ${g.scores[stateV2.giftSort]}/5</div><button class="primary" data-v3="buy-product" data-value="${g.id}">${say('联系购买','Contact to buy')} ↗</button></div></article>`).join(''):`<div class="empty-state"><h4>${say('当前条件没有匹配的手信','No gifts match these filters')}</h4><button class="secondary" data-v2="reset-gifts">${say('重置筛选','Reset filters')}</button></div>`}</div>`;
};
function buyProductV3(id){const g=GIFTS.find(g=>g.id===id);if(!g)return;stateV3.contactProduct=id;const node=dialogV3('purchase-dialog');const message=say('你好，我想咨询：','Hello, I would like to ask about: ')+pick(g.name)+say('。请告知实际款式、价格与配送方式。','. Please confirm available designs, price and delivery.');node.innerHTML=dialogHeader(say('联系购买','Contact to buy'))+`<div class="purchase-summary"><img src="${productImage(g)}" width="180" height="180" alt="${attr(pick(g.name))}"><div><h3>${pick(g.name)}</h3><p>${pick(g.tip)}</p></div></div><label class="share-label" for="purchase-message">${say('询价内容','Inquiry text')}</label><textarea id="purchase-message">${esc(message)}</textarea><button class="secondary" data-v3="copy-inquiry">${say('复制询价内容','Copy inquiry')}</button><p class="status" id="purchase-status" role="status"></p>${contactsV3()}<p class="fine-print">${say('请向联系人确认实际商品、总价和交付安排。本页不提交订单或收款。','Confirm the actual item, total price and delivery with the contact. This page does not place orders or take payments.')}</p>`;node.showModal();}
async function copyV3(text,statusId,fallbackId){const target=document.getElementById(statusId);try{await navigator.clipboard.writeText(text);target.textContent=say('已复制。','Copied.');}catch{target.textContent=say('请在文本框中选中并手动复制。','Select the text in the box and copy it manually.');const field=document.getElementById(fallbackId);field.value=text;field.focus();field.select();}}
document.addEventListener('click',e=>{const btn=e.target.closest('[data-v3]');if(!btn)return;const action=btn.dataset.v3,value=btn.dataset.value;
 if(action==='duration'){stateV3.duration=value;renderTravelV2();document.querySelector(`[data-v3=duration][data-value=${value}]`).focus({preventScroll:true});}
 if(action==='open-route')openRouteV3(value);
 if(action==='share-route')shareRouteV3(value);
 if(action==='close-dialog')btn.closest('dialog').close();
 if(action==='image')showImageV3(btn.src,btn.alt);
 if(action==='qr'){const c=CONTACTS[value];showImageV3(c.image,c.label+' QR');}
 if(action==='full-route-image'){const r=V3_ROUTES.find(r=>r.id===value);showImageV3(r.cover,pick(r.theme));}
 if(action==='dish-image')showImageV3('assets/dish-'+value+'-v3.webp',pick(V3_CUISINES[value])+' · AI');
 if(action==='product-image'){const g=GIFTS.find(g=>g.id===value);showImageV3(productImage(g),pick(g.name)+' · AI');}
 if(action==='copy-link')copyV3(routeUrlV3(V3_ROUTES.find(r=>r.id===value)),'share-status','share-text');
 if(action==='copy-text')copyV3(routeTextV3(V3_ROUTES.find(r=>r.id===value)),'share-status','share-text');
 if(action==='more-food'){stateV3.foodPage++;renderFoodV2();}
 if(action==='reset-food'){Object.assign(stateV3,{foodSearch:'',foodCuisine:'all',reviewOnly:false,foodPage:1});renderFoodV2();}
 if(action==='buy-product')buyProductV3(value);
 if(action==='copy-inquiry')copyV3(document.querySelector('#purchase-message').value,'purchase-status','purchase-message');
 if(action==='route-to-guide'){const r=V3_ROUTES.find(r=>r.id===value);draft.duration=String(Object.keys(V3_DURATION).indexOf(r.duration));draft.interests=pick(r.title);document.querySelector('#route-dialog').close();render();setTab('guide');document.querySelector('#trip-planner').scrollIntoView({block:'start'});document.querySelector('#guide-form textarea').focus({preventScroll:true});}
});
document.addEventListener('keydown',e=>{if(e.target.matches('img[data-v3=image]')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();showImageV3(e.target.src,e.target.alt);}});
document.addEventListener('input',e=>{if(e.target.id==='food-search'&&!e.isComposing){stateV3.foodSearch=e.target.value;stateV3.foodPage=1;renderFoodV2();const input=document.querySelector('#food-search');input.focus({preventScroll:true});}});
document.addEventListener('change',e=>{if(e.target.id==='food-cuisine'){stateV3.foodCuisine=e.target.value;stateV3.foodPage=1;renderFoodV2();document.querySelector('#food-cuisine').focus({preventScroll:true});}if(e.target.id==='review-only'){stateV3.reviewOnly=e.target.checked;stateV3.foodPage=1;renderFoodV2();document.querySelector('#review-only').focus({preventScroll:true});}});
const v2RenderV3=render;
render=function(){v2RenderV3();enhanceImagesV3();};
translations.zh.edition='城市漫游手册 · VOL. 03';translations.en.edition='THE CITY EDIT · VOL. 03';
translations.zh.heroDesc='60 条路线，100+ 家餐厅，和一份中国心意。<br>把旅行笔记装进口袋，让深圳离你更近。';translations.en.heroDesc='60 routes, 100+ restaurants, and thoughtful gifts.<br>Your next Shenzhen story starts here.';
translations.zh.disclaimer='独立旅行指南，非 APEC 官方网站。旅行与商品图片为 AI 示意，地陪为演示档案；用户评论为有来源的摘录或译文。';translations.en.disclaimer='Independent guide, not an official APEC website. Travel and product images are AI illustrations; guide profiles are demos. User reviews are sourced excerpts or translations.';
translations.zh.sourceNote='整理于 2026-09-24。路线与预算为编辑建议；餐厅摘录保留平台作者与日期，译文不代表平台官方翻译。完整评论请查看卡片链接。POI 位置为片区近似点，不是精确门店入口。';translations.en.sourceNote='Compiled September 24, 2026. Routes and budgets are editorial. Review excerpts retain public author/date; translations may be editorial or platform-rendered. Read full reviews via each card. POIs are approximate area points, not surveyed entrances.';
render();
const initialRoute=new URLSearchParams(location.search).get('route');if(V3_ROUTES.some(r=>r.id===initialRoute)){stateV3.duration=V3_ROUTES.find(r=>r.id===initialRoute).duration;renderTravelV2();setTab('travel',false);openRouteV3(initialRoute);}
