'use strict';
GIFTS.splice(0,GIFTS.length,...V5_GIFTS);
const V5_CATEGORIES={all:bi('全部','All'),tea:bi('茶叶','Tea'),magnet:bi('冰箱贴','Magnets'),scarf:bi('丝巾','Scarves'),fan:bi('折扇','Folding fans'),porcelain:bi('瓷器','Porcelain'),panda:bi('熊猫玩偶','Panda plush'),incense:bi('香薰','Fragrance'),seal:bi('印章','Seals')};
stateV4.giftCategory='all';stateV4.giftRegion='all';stateV4.giftPage=1;
function reviewRecordsV5(r){const found=V5_REVIEWS[r.id]||[];return found.length?found:[{id:r.id,author:r.reviewAuthor||say('平台用户','Platform user'),text:bi(r.reviewTextZh,r.reviewTextEn),score:null,date:r.reviewDate,source:r.reviewSource,platform:r.reviewPlatform||'Tripadvisor'}];}
function reviewRowV5(c){return `<a class="review-row-v5" href="${attr(c.source)}" target="_blank" rel="noopener noreferrer" title="${attr(c.author+' · '+c.platform+(c.sourceVisibility==='public_folded'?say('（公开折叠点评）',' (public folded review)'):'')+' · '+(c.date||'')+' · '+pick(c.text))}"><span class="review-person-v5"><b>${esc(c.author)}</b>${c.score?`<span class="review-score">★ ${esc(c.score)}/5</span>`:''}${c.date?`<time>${esc(c.date)}</time>`:''}</span><span class="review-summary-v5">${esc(pick(c.text))}</span><span aria-hidden="true">↗</span></a>`;}
function venueSliderV5(r){return `<div class="venue-slider-v5" aria-label="${attr(say('店铺相册，左右滑动','Venue photos, swipe horizontally'))}">${restaurantPhotosV4(r).map((p,i)=>`<button data-v4="venue" data-id="${attr(r.id)}" aria-label="${attr(say('查看店铺详情，第','Open venue, photo ')+(i+1))}"><img src="${attr(p.src)}" alt="${attr(lang==='zh'?r.nameZh:r.nameEn)} · ${i+1}" loading="lazy" referrerpolicy="no-referrer"><span>${i+1} / ${restaurantPhotosV4(r).length}</span></button>`).join('')}</div>`;}
restaurantCardV3=function(r){const zh=lang==='zh';const reviews=reviewRecordsV5(r);const feature=V4_RESTAURANT_MEDIA[r.id]?.feature||featureV4(r);return `<article class="restaurant-card">${venueSliderV5(r)}<div class="restaurant-body"><div class="restaurant-meta"><span>${esc(zh?r.cuisineZh:r.cuisineEn)}</span><span>~${r.distance.toFixed(1)} km</span></div><button class="venue-title-v5" data-v4="venue" data-id="${attr(r.id)}"><h4>${esc(zh?r.nameZh:r.nameEn)} ↗</h4></button><p class="venue-feature">${esc(pick(feature))}</p><p class="restaurant-area">⌖ ${esc(zh?r.areaZh:r.areaEn)}</p><div class="review-list-v5">${reviews.slice(0,2).map(reviewRowV5).join('')}</div><div class="restaurant-links"><button class="text-button" data-v4="venue" data-id="${attr(r.id)}">${say('店铺详情与点评','Venue & reviews')} ↗</button><a href="${mapLink(r.nameZh)}" target="_blank" rel="noopener noreferrer">${say('导航','Map')} ↗</a></div></div></article>`;};
openVenueV4=function(id){const r=V3_RESTAURANTS.find(x=>x.id===id);if(!r)return;const media=V4_RESTAURANT_MEDIA[id];const reviews=reviewRecordsV5(r);const n=dialogV3('venue-dialog',true);n.innerHTML=dialogHeader(esc(lang==='zh'?r.nameZh:r.nameEn))+`<p class="venue-feature">${esc(pick(media?.feature||featureV4(r)))}</p>`+galleryV4(restaurantPhotosV4(r),say('店铺与菜品相册','Venue & food album'))+`<div class="venue-review-heading"><h3>${say('食客点评','Diner reviews')}</h3><span>${reviews.length} ${say('条已收录','collected')}</span></div><p class="fine-print review-summary-note">${say('以下为公开食客点评的摘要／译文，点击一行可阅读原文。','Summaries / translations of public diner reviews. Open a row to read the original.')}</p><div class="review-list-v5 venue-reviews-v5">${reviews.map(reviewRowV5).join('')}</div><div class="detail-actions"><a class="secondary" href="${attr(r.reviewSource)}" target="_blank" rel="noopener noreferrer">${say('查看平台全部点评','All platform reviews')} ↗</a><a class="primary" href="${mapLink(r.nameZh)}" target="_blank" rel="noopener noreferrer">${say('地图导航','Open map')} ↗</a></div>`;n.showModal();};
renderGiftsV2=function(){
 const q=stateV4.giftSearch.trim().toLowerCase();const items=GIFTS.filter(g=>(stateV4.giftCategory==='all'||g.category===stateV4.giftCategory)&&(stateV4.giftRegion==='all'||g.region.en===stateV4.giftRegion)&&(!q||(g.name.zh+' '+g.name.en+' '+g.merchantTitle+' '+g.sku+' '+g.origin.zh+' '+g.origin.en).toLowerCase().includes(q))).sort((a,b)=>b.scores[stateV4.giftSort]-a.scores[stateV4.giftSort]||a.rank-b.rank);
 const regions=[...new Map(GIFTS.map(g=>[g.region.en,g.region])).values()];const count=20,pages=Math.max(1,Math.ceil(items.length/count));stateV4.giftPage=Math.min(stateV4.giftPage,pages);const visible=items.slice((stateV4.giftPage-1)*count,stateV4.giftPage*count);
 document.querySelector('#panel-gifts').innerHTML=panelHeading('SOMETHING CHINESE, SOMETHING PERSONAL',say('带走一份中国心意','A little China to take home'),say('茶叶、冰箱贴、丝巾、折扇、瓷器、熊猫、香薰、印章。8 个品类，每类 20 款。','Tea, magnets, scarves, fans, porcelain, pandas, fragrance and seals. Eight categories, twenty items each.'))+chipsV3(Object.entries(V5_CATEGORIES).map(([id,l])=>[id,pick(l)]),'gift-category-v4',stateV4.giftCategory)+`<div class="gift-filters-v4"><label>${say('找一份礼物','Find a gift')}<input type="search" id="gift-search-v4" value="${attr(stateV4.giftSearch)}" placeholder="${say('例如：熊猫、苏绣、龙井','Try panda, embroidery, Longjing')}"></label><label>${say('商品标注产地','Listed origin')}<select id="gift-region-v4"><option value="all">${say('全部','All')}</option>${regions.map(r=>`<option value="${attr(r.en)}" ${stateV4.giftRegion===r.en?'selected':''}>${esc(pick(r))}</option>`).join('')}</select></label><label>${say('排序','Sort')}<select id="gift-sort-v4">${[['gift',say('品类精选','Category picks')],['portable',say('便携优先','Packability')],['culture',say('文化特色','Cultural character')]].map(([v,l])=>`<option value="${v}" ${stateV4.giftSort===v?'selected':''}>${l}</option>`).join('')}</select></label></div><div class="collection-bar"><span role="status">${items.length} ${say('款商品','products')} · ${stateV4.giftPage}/${pages}</span><span>${say('联系确认价格与配送','Contact for prices & delivery')}</span></div><div class="product-grid">${visible.map(g=>`<article class="product-card"><button class="product-picture" data-v5="gift-detail" data-id="${attr(g.id)}" aria-label="${attr(pick(g.name))}"><img src="${attr(productImage(g))}" alt="${attr(pick(g.name))}" loading="lazy" referrerpolicy="no-referrer"><span class="product-tag">${esc(pick(V5_CATEGORIES[g.category]))}</span></button><div class="product-body"><button class="gift-title-v5" data-v5="gift-detail" data-id="${attr(g.id)}"><h4>${esc(pick(g.name))}</h4></button><p class="product-description">${esc(pick(g.desc))}</p><p class="product-fit">${esc(pick(g.spec))}</p><div class="gift-card-actions-v5"><button class="secondary" data-v5="gift-detail" data-id="${attr(g.id)}">${say('商品详情','Details')}</button><button class="primary" data-v3="buy-product" data-value="${attr(g.id)}">${say('联系购买','Contact to buy')} ↗</button></div></div></article>`).join('')||`<div class="empty-state"><p>${say('没有匹配的商品','No matching products')}</p><button class="secondary" data-v4="gift-reset">${say('清除筛选','Clear filters')}</button></div>`}</div><nav class="pagination-v4" aria-label="${say('商品分页','Product pages')}"><button class="secondary" data-v4="gift-prev" ${stateV4.giftPage===1?'disabled':''}>← ${say('上一页','Previous')}</button><span>${stateV4.giftPage} / ${pages}</span><button class="secondary" data-v4="gift-next" ${stateV4.giftPage===pages?'disabled':''}>${say('下一页','Next')} →</button></nav>`;
};

function giftVerificationV6(g){
 const v=g.verification;if(!v)return '';
 const exact=v.verificationLevel==='same_sku_partial_listing';
 const unknown=say('尚未核实，请联系确认','Unverified; contact to confirm');
 const field=(label,value)=>`<dt>${label}</dt><dd>${esc(value||unknown)}</dd>`;
 return `<section class="product-verification-v6"><h4>${say('同款资料核对','Selected item verification')}</h4><p class="fine-print">${exact?say('已核对京东公开列表中的 SKU、名称和已选款式。以下仅为商家列表标注。','SKU, title and selected design match the public JD listing. Fields below are merchant listing claims.'):say('当前公开列表未找到这个 SKU，同款品牌、型号与规格仍待核实。','This SKU is absent from the current public listing. Brand, model and specification remain unverified.')}</p><dl class="gift-specs-v5">${field(say('商家标注品牌','Listed brand'),exact?v.brand.value:null)}${field(say('厂家型号','Manufacturer model'),v.model.value)}${field(say('已选款式','Selected design'),exact?v.style.value:null)}${field(say('公开标注规格','Listed specification'),exact?v.specification.value:null)}</dl><p class="fine-print">${say('待确认：','To confirm: ')}${esc(lang==='zh'?v.missingFields.join('、'):v.missingFieldsEn.join(', '))}</p><a href="${attr(v.source)}" target="_blank" rel="noopener noreferrer">${say('核对资料来源','Verification source')} ↗</a></section>`;
}
function giftDetailV5(id){const g=GIFTS.find(x=>x.id===id);if(!g)return;const n=dialogV3('gift-detail-dialog',true);const pictures=g.images.map(src=>({src,caption:g.name,source:g.listingSource}));n.innerHTML=dialogHeader(esc(pick(g.name)))+galleryV4(pictures,say('商品图片','Product photos'))+`<p class="note-lead">${esc(pick(g.desc))}</p><dl class="gift-specs-v5"><dt>${say('品类','Category')}</dt><dd>${esc(pick(V5_CATEGORIES[g.category]))}</dd><dt>SKU</dt><dd>${esc(g.sku)}</dd><dt>${say('已取得款式','Listed design')}</dt><dd>${esc(lang==='zh'?g.spec.zh:g.spec.en)}</dd><dt>${say('商品标注产地','Listed origin')}</dt><dd>${esc(pick(g.origin))}</dd>${g.material?`<dt>${say('标题标注材质','Material in listing')}</dt><dd>${esc(lang==='zh'?g.material:materialEnV5(g.material))}</dd>`:''}${g.dimensions?`<dt>${say('标题标注规格','Size / quantity in listing')}</dt><dd>${esc(g.dimensions)}</dd>`:''}<dt>${say('资料日期','Collected')}</dt><dd>2026-10-01</dd><dt>${say('价格与库存','Price & stock')}</dt><dd>${say('请联系确认','Contact to confirm')}</dd></dl>${giftVerificationV6(g)}${g.variants.length?`<h4>${say('公开可见款式','Publicly listed designs')}</h4><div class="gift-variants-v5">${g.variants.slice(0,16).map(v=>`<span>${esc(v)}</span>`).join('')}</div>`:''}<details class="merchant-info-v5"><summary>${say('商品资料与来源','Product information & source')}</summary><p lang="zh-CN">${esc(g.merchantTitle)}</p><p class="fine-print">${say('已整理公开列表中的图片、款式和规格。完整详情页目前访问受限，其他参数请联系确认。','Photos, designs and specifications were collected from the public listing. The full detail page is currently access-restricted; confirm other parameters with the contact.')}</p><a href="${attr(g.listingSource)}" target="_blank" rel="noopener noreferrer">${say('资料页','Listing')} ↗</a> · <a href="${attr(g.source)}" target="_blank" rel="noopener noreferrer">${say('原始商品页','Original product')} ↗</a></details><div class="detail-actions"><button class="primary" data-v3="buy-product" data-value="${attr(g.id)}">${say('联系购买','Contact to buy')} ↗</button></div>`;n.showModal();}
function materialEnV5(s){return {'桑蚕丝':'Mulberry silk','真丝':'Silk','绢布':'Fabric fan leaf','宣纸':'Xuan paper','竹':'Bamboo','青田石':'Qingtian stone','寿山石':'Shoushan stone','陶瓷':'Ceramic','瓷':'Porcelain','金属':'Metal','木质':'Wood','毛绒':'Plush'}[s]||s;}
renderGuidesV2=function(){let mount=document.querySelector('#guide-directory');if(!mount){mount=document.createElement('section');mount.id='guide-directory';document.querySelector('#panel-guide').prepend(mount);document.querySelector('.guide-layout').id='trip-planner';}const gs=GUIDES.filter(g=>(stateV2.gender==='all'||g.gender===stateV2.gender)&&(stateV2.specialty==='all'||g.specialty===stateV2.specialty));mount.innerHTML=panelHeading('PEOPLE WITH A LITTLE MORE STORY',say('一起走走，也聊聊生活','Take a walk. Share a perspective.'),say('学生、白领与文化爱好者，选一个与你合拍的旅行风格。','Students, professionals and culture enthusiasts: find a travel style that suits you.'))+`<p class="guide-demo-note">${say('10 位虚构成年演示档案，个人介绍与语言能力为示例，实际服务需联系确认。','10 fictional adult demo profiles. Introductions and languages are examples; contact us to discuss actual services.')}</p><div class="guide-filters">${filters([['all',say('全部','All')],['female',say('女生','Women')],['male',say('男生','Men')]],'gender',stateV2.gender)}<label class="sr-only" for="guide-specialty">${say('特色','Interests')}</label><select id="guide-specialty">${Object.entries(SPECIALTIES).map(([id,l])=>`<option value="${id}" ${stateV2.specialty===id?'selected':''}>${pick(l)}</option>`).join('')}</select></div><div class="guide-grid">${gs.map(g=>`<article class="guide-card"><div class="portrait"><img src="${attr(g.image)}" width="900" height="1100" alt="${attr(g.name)}" loading="lazy"></div><div class="guide-card-body"><div class="guide-person-v5"><h4>${esc(g.name)}</h4><span class="badge">${esc(pick(g.role))}</span></div><h5>${esc(pick(g.tagline))}</h5><p>${esc(pick(g.bio))}</p><div class="guide-traits-v5">${pick(g.traits).map(t=>`<span># ${esc(t)}</span>`).join('')}</div><span class="guide-language">${pick(g.languages)}</span><button class="secondary" data-v2="choose-guide" data-value="${g.id}" aria-pressed="${stateV2.selectedGuide===g.id}">${stateV2.selectedGuide===g.id?say('已选择此风格','Style selected'):say('按此风格安排行程','Plan in this style')} ↗</button></div></article>`).join('')||`<div class="empty-state">${say('没有匹配的档案','No matching profiles')}</div>`}</div><div class="planner-heading"><span class="eyebrow dark">YOUR TRIP BRIEF</span><h3>${say('把想法整理好，再出发','Turn an idea into a trip brief')}</h3><p id="selected-style">${stateV2.selectedGuide?say('当前示例风格：','Selected demo style: ')+GUIDES.find(g=>g.id===stateV2.selectedGuide).name:say('也可以直接描述你的需求。','Or describe your needs directly.')}</p></div>`;};
document.addEventListener('click',e=>{const b=e.target.closest('[data-v5]');if(b?.dataset.v5==='gift-detail')giftDetailV5(b.dataset.id);});
const v4RenderV5=render;render=function(){v4RenderV5();document.querySelectorAll('img').forEach(i=>{i.alt=i.alt.replace(/AI[-\s]?generated(?: impression of | fictional adult guide|的虚构成年地陪头像)?|AI\s*生成的?|\s*·\s*AI/gi,'').trim();});enhanceImagesV3();};
translations.zh.edition='城市漫游手册 · VOL. 05';translations.en.edition='THE CITY EDIT · VOL. 05';translations.zh.heroDesc='60 条路线，100+ 条餐厅推荐，160 款特色礼物。<br>从真实风景出发，找到你的深圳。';translations.en.heroDesc='60 routes, 100+ dining picks and 160 distinctive gifts.<br>Discover your own Shenzhen.';
translations.zh.sourceNote='更新日期：2026 年 10 月 1 日。餐厅显示可核验的用户点评摘要，条数按公开可取得的记录展示。礼物为京东公开列表按品类筛选的 160 个 SKU，每类 20 款；完整详情页受访问限制，已取得的图片、款式、标题规格与来源在商品详情中展示。价格、库存和服务请联系确认。';translations.en.sourceNote='Updated October 1, 2026. Dining reviews summarize verifiable public records; counts reflect available records. Gifts comprise 160 JD listing SKUs, twenty per category. Full detail pages are access-restricted; product details display collected photos, designs, title specifications and sources. Confirm price, stock and services with the contact.';
translations.zh.disclaimer='独立旅行指南，非 APEC 官方网站。景点、餐厅及商品图片附来源；地陪为虚构演示档案；用户评论为有来源的摘要或译文。';translations.en.disclaimer='Independent guide, not an official APEC website. Destination, venue and product photos link to their sources; guide profiles are fictional demos. Reviews are sourced summaries or translations.';
render();const deepV5=new URLSearchParams(location.search).get('route');if(deepV5)openRouteV3(deepV5);
