export const LAYOUT = {
  tileSizeMin: 48,
  tileSizeMax: 92,
  tileGap: 6,
  contentPadding: 16,
  maxContentWidth: 480,
  overlapRatio: 0.85,
  overlapRatioMin: 0.78,
  overlapCandidates: [0.8, 0.83, 0.85] as const,
  desktopMinWidth: 900,
  desktopMinHeight: 700,
  desktopMinGameHeight: 700,
  headerMinHeight: 76,
  trayBottomSpace: 118,
  trayGap: 5,
  trayLabelOffset: 24,
  sectionGap: 14,
  toolButtonMinSize: 44,
} as const;

export const COLORS = {
  skyTop: 0x8fd0ff,
  /** 未获得的星星：去色偏冷灰，与已获得的暖金拉开对比 */
  resultStarUnearnedTint: 0xaebbc5,
  skyBottom: 0xe8f5ff,
  cloud: 0xffffff,
  tileBase: 0xfff6e3,
  tileStroke: 0xb08355,
  tileShadow: 0x8c643c,
  title: '#684e7a',
  text: '#6e573e',
  tray: 0xf6ead2,
  trayStroke: 0xc9ad84,
  paw: 0xff8fa3,
  grass: 0x5fbf6a,
  watering: 0x54a8e0,
  bell: 0xffc93c,
  fish: 0xff9a5c,
  yarn: 0xb98be0,
  bone: 0xefe6d2,
  flowerpot: 0xc97b4a,
} as const;

/**
 * 成品 UI 视觉参数集中在这里，避免 Scene 内再次出现彼此冲突的临时倍率与颜色。
 * Tile 源素材的非透明主体占 256px 画布的 174px（67.97%）。
 */
export const GAME_UI = {
  tileSourceSubjectRatio: 174 / 256,
  tileFrameSafeRatio: 206 / 256,
  boardIconCanvasRatio: 1,
  trayIconCanvasRatio: 0.9,
  surfaceCream: 0xfff8e9,
  surfaceRadius: 16,
  surfaceFillAlpha: 0.92,
  surfaceStrokeAlpha: 0.72,
  surfaceHighlightAlpha: 0.78,
  surfaceShadowAlpha: 0.11,
  surfaceShadowOffset: 3,
  headerTitleSize: 22,
  headerMetaSize: 13,
  headerCountSize: 17,
  buttonRadius: 13,
  buttonStrokeWidth: 1.5,
  buttonShadowOffset: 3,
  buttonPressedOffset: 2,
  buttonPressedShadowScale: 0.35,
  buttonPrimaryStrokeAlpha: 0.65,
  buttonSecondaryStrokeAlpha: 0.45,
  buttonDangerStrokeAlpha: 0.45,
  buttonPrimaryShadowAlpha: 0.14,
  buttonSecondaryShadowAlpha: 0.08,
  buttonDangerShadowAlpha: 0.04,
  toolIconSize: 33,
  toolIconGap: 8,
  toolBadgeRadius: 9,
  toolBadgeEdgeInset: 7,
  surfaceStroke: 0xffffff,
  controlStroke: 0xb08355,
  softShadow: 0x56758a,
  disabledFill: 0xebe7de,
  disabledStroke: 0xbab1a6,
  primaryFill: 0xffd76b,
  secondaryFill: 0xfffbf2,
  dangerFill: 0xf4f0ec,
  textSecondary: '#496d83',
  textMuted: '#6b5c52',
  textDisabled: '#8c847a',
  /** 暂存槽面板三档配色：常态奶油 / 5-6 格预警暖黄 / 危险与满格暖红 */
  trayPanelPressureFill: 0xfff3df,
  trayPanelDangerFill: 0xffeee8,
  trayPanelStroke: 0xffffff,
  trayPanelPressureStroke: 0xd99a3c,
  trayPanelDangerStroke: 0xd66b4d,
  trayPanelStrokeAlpha: 0.8,
  trayPanelStrokeWidth: 1.5,
  trayLabelPressureColor: '#a9681f',
  trayLabelDangerColor: '#c95e46',
  trayPanelAlpha: 0.88,
  trayEmptySlotAlpha: 0.66,
  trayOccupiedSlotAlpha: 1,
  trayOccupiedHighlight: 0xffe5a8,
  trayOccupiedHighlightAlpha: 0.14,
  trayPairGlow: 0xffc45c,
  trayPairGlowAlpha: 0.58,
  trayPairGlowEnterAlpha: 0.25,
  trayWarningPulseAlpha: 0.82,
  trayPairGlowWidth: 2,
  trayPairGlowDuration: 400,
  tileCoveredFrameAlpha: 0.86,
  tileCoveredIconAlpha: 1,
  tileCoveredOverlay: 0x253746,
  tileCoveredOverlayAlpha: 0.03,
  tileActiveShadowAlpha: 0.12,
  tileActiveShadowOffset: 3,
  tileActiveOutline: 0xd4a657,
  tileActiveOutlineAlpha: 0.35,
  tileActiveOutlineWidth: 1,
  backgroundWashTopAlpha: 0.04,
  backgroundWashBottomAlpha: 0.14,
  settingsVisualSize: 32,
  settingsHitSize: 48,
  settingsRestAlpha: 0.9,
  settingsDisabledAlpha: 0.5,
  helpPanelRadius: 18,
  helpPanelFillAlpha: 0.95,
  helpPanelShadowAlpha: 0.12,
  helpBackHitHeight: 44,
  helpHeaderIconSize: 52,
  helpVisualHeight: 82,
  helpSectionRadius: 12,
  helpButtonHeight: 44,
  resultOverlayAlpha: 0.4,
  resultPanelWidthRatio: 0.84,
  resultPanelMaxWidth: 320,
  resultPanelHeight: 310,
  resultFailPanelHeight: 250,
  resultStarSize: 38,
  resultStarUnearnedAlpha: 0.48,
  resultPanelEnterAlpha: 0.72,
  resultPanelEnterScale: 0.86,
  resultStarGap: 44,
  resultTitleSize: 26,
  resultBodySize: 14,
  resultStatHeight: 44,
  resultStatRadius: 10,
  resultButtonHeight: 46,
  resultButtonGap: 8,
  resultPanelPadding: 16,
  resultPanelEnterMs: 180,
  resultContentFadeMs: 140,
  resultContentDelayMs: 70,
  resultStarEnterMs: 220,
  resultStarInitialDelayMs: 90,
  resultStarStaggerMs: 90,
  resultParticleDelayMs: 80,
  resultParticleMs: 360,
  confirmationPanelMaxWidth: 330,
  confirmationPanelHeight: 190,
  confirmationPanelRadius: 18,
} as const;

export const PROTOTYPE_UI = {
  cornerRatio: 0.12,
  tileStrokeWidth: 2,
  shadowOffset: 3,
  iconRatio: 0.56,
  titleFontSize: 24,
  subtitleFontSize: 14,
  tileLabelMinSize: 16,
  tileLabelRatio: 0.38,
  trayLabelMinSize: 13,
  buttonFontSize: 16,
  toolButtonGap: 8,
  backgroundAlpha: 0.2,
} as const;
